# Generated by Django 4.2.6 on 2023-10-21 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Chat",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("user_id", models.CharField(max_length=80)),
                ("chat_id", models.CharField(max_length=80)),
                ("chat_history", models.TextField()),
                (
                    "model_type",
                    models.CharField(
                        choices=[("gpt-4-0613", "GPT-4 Model"), ("gpt-3.5-turbo-0613", "GPT-3.5 Turbo Model")],
                        default="gpt-3.5-turbo-0613",
                        max_length=20,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Audio",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "type",
                    models.CharField(
                        choices=[("input", "Input"), ("output", "Output")], default="input", max_length=6
                    ),
                ),
                ("audio_data", models.BinaryField()),
                (
                    "chat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="audios", to="app.chat"
                    ),
                ),
            ],
        ),
    ]
