# Generated by Django 4.2.6 on 2023-10-23 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0002_scenario"),
    ]

    operations = [
        migrations.AddField(
            model_name="chat",
            name="scenario",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chats",
                to="app.scenario",
            ),
        ),
    ]
